### ISSUE TITLE
Behaviour on deploys

### ISSUE THREAD

**Issue by j3ll3nl** [reload/deployotron#41]
We are testing deployments with Deployotron since a couple of days and we are running into some strange behaviour. 

1. When we are deploting we are seeing only "run command:" without any information. is that good behaviour? 
![snapshot](https://cloud.githubusercontent.com/assets/10446794/8201615/f1256ca4-14d2-11e5-935b-1c584aef0be8.png)
2. After deploying we are detached from the branch and when doing a new deployment it fetches from the detached branch so that it won't find new commits.

How should this work?

**Comment by xendk** [comment]
1. Not really. Did you upgrade the lately, and are you running the master branch? There was some refactoring around that a few days ago. How does your alias look?

2. A detached branch is the expected behaviour. This shouldn't be a problem for git fetch as it fetches all changes from origin per default. Deployotron really don't care about branches, it translates branches/tags to SHAs of specific commits early on. Do you have any other remotes than origin configured in the repository on the server?

**Comment by j3ll3nl** [comment]
1. I downloaded 2.1.0

The alias look like this:
```php
<?php

// The local environment variables here.
$env_settings = array (
  'root' => '/httpdocs',
  'uri' => 'example.nl',
  'deployotron' => array(
    'branch' => 'release/acceptation', // Default is master
    'dump-dir' => '/deployment/shared/default/tmp', // Defaults to /tmp.
    'num-dumps' => 5, // Defaults to 5. 0 for unlimited.
    'post-deploy' => array(
    ),
  ),
);

// These are the settings per environment.
$aliases['example_acc'] = array (
    'uri' => 'example.nl',
  ) + $env_settings;

$aliases['example2_acc'] = array (
    'uri' => 'example2.nl',
  ) + $env_settings;

$aliases['example3_acc'] = array (
    'uri' => 'example3.nl',
  ) + $env_settings;

?>
```

2. No, we don't but when deploying the second time it didn't show us new commits. Maybe this problem has to do with problem 1?

**Comment by xendk** [comment]
1. Ah, the problem is the empty post-deploy array. I should add a check for empty values.

2. And you pushed in the meantime?

**Comment by j3ll3nl** [comment]
Thnx for the update in the code.

I have tried to get it working on another project and it seems it doesn't fetch the changes from the git-server.

**Comment by xendk** [comment]
What's the error message?
